pipeline:
    test:
        image: mongo:3.2.10
        commands:
            - sleep 20
            - |
              mongo --host mongo --eval "{ ping: 1 }"            
        
services:
    mongo:
        image: mongo:3.2.10
        command: [ --smallfiles ]
